search:
    pattern:        /search
    defaults:       { _controller: knp_bundles.controller.repo:searchAction }
    requirements:   { _method: "GET"}

latest:
    pattern:        /latest
    defaults:       { _controller: knp_bundles.controller.repo:listLatestAction, class: Bundle }
    requirements:   { _method: "GET" }

api:
    pattern:        /api
    defaults:       { _controller: knp_bundles.controller.main:apiAction }
    requirements:   { _method: "GET" }

project_list:
    pattern:        /project/{sort}
    defaults:       { _controller: knp_bundles.controller.repo:listAction, class: Project, sort: best }
    requirements:   { _method: "GET", sort: "(best|updated|newest)"}

user_list:
    pattern:        /developer/{sort}
    defaults:       { _controller: knp_bundles.controller.user:listAction, sort: name }
    requirements:   { _method: "GET", sort: "(name|best)"}

bundle_list:
    pattern:        /{sort}
    defaults:       { _controller: knp_bundles.controller.repo:listAction, class: Bundle, sort: best }
    requirements:   { _method: "GET", sort: "(best|updated|newest)"}

user_bundle_list:
    pattern:        /{name}/bundles
    defaults:       { _controller: knp_bundles.controller.user:bundlesAction }
    requirements:   { _method: "GET", format: "(json|js)" }

user_projects_list:
    pattern:        /{name}/projects
    defaults:       { _controller: knp_bundles.controller.user:projectsAction }
    requirements:   { _method: "GET", format: "(json|js)" }

user_show:
    pattern:        /{name}/profile 
    defaults:       { _controller: knp_bundles.controller.user:showAction }
    requirements:   { _method: "GET"}

repo_show:
    pattern:        /{username}/{name}
    defaults:       { _controller: knp_bundles.controller.repo:showAction }
    requirements:   { _method: "GET", format: "(html|json|js)", name: ".+" }
