search:
    pattern:        /search
    defaults:       { _controller: KnpBundlesBundle:Bundle:search }
    requirements:   { _method: "GET"}

latest:
    pattern:        /latest
    defaults:       { _controller: KnpBundlesBundle:Bundle:listLatest }
    requirements:   { _method: "GET" }

api:
    pattern:        /api
    defaults:       { _controller: KnpBundlesBundle:Main:api }
    requirements:   { _method: "GET" }

evolution:
    pattern:        /evolution
    defaults:       { _controller: KnpBundlesBundle:Bundle:evolution }
    requirements:   { _method: "GET" }

user_list:
    pattern:        /developer/{sort}
    defaults:       { _controller: KnpBundlesBundle:User:list, sort: name }
    requirements:   { _method: "GET", sort: "(name|best)"}

bundle_list:
    pattern:        /{sort}
    defaults:       { _controller: KnpBundlesBundle:Bundle:list, sort: trend }
    requirements:   { _method: "GET", sort: "(best|updated|newest|trend)"}

user_bundle_list:
    pattern:        /{name}/bundles
    defaults:       { _controller: KnpBundlesBundle:User:bundles }
    requirements:   { _method: "GET", format: "(json|js)" }

user_show:
    pattern:        /{name}/profile 
    defaults:       { _controller: KnpBundlesBundle:User:show }
    requirements:   { _method: "GET"}

bundle_show:
    pattern:        /{username}/{name}
    defaults:       { _controller: KnpBundlesBundle:Bundle:show }
    requirements:   { _method: "GET", format: "(html|json|js)", name: ".+" }
