imports:
    - { resource: config_dev.yml }

doctrine:
    dbal:
        default_connection: default
        connections:
            default:
                driver:   pdo_mysql
                dbname:   s2b_dev
                user:     root
                password: ~
