framework:
    charset:          UTF-8
    csrf_protection:  true
    secret:           betterPuttingThisInTheLocalConfigFile
    router:           { resource: "%kernel.root_dir%/config/routing.yml" }
    validation:       { enabled: true, enable_annotations: true }
    templating:       { engines: ['twig', 'php'] }
    session:
        default_locale: en
        lifetime:       3600
        auto_start:     true
    translator:    ~


# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%

# Markdown Configuration
knplabs_markdown:
    parser: ~       # Enable the parser service

# Time Configuration
knplabs_time: ~     # Enable the time helper

# Menu Configuration
knplabs_menu:
    twig: true

# Paginator Configuration
knplabs_paginator:
    templating: ~

# Symfony2Bundles Configuration
knplabs_symfony2_bundles: ~

# Gravatar Configuration
gravatar: ~

# Doctrine Configuration
doctrine:
    dbal:
        default_connection: default
        connections:
            default:
                driver:   pdo_mysql
                dbname:   s2b_prod
                user:     root
                password: ~
    orm:
        default_entity_manager: default
        auto_generate_proxy_classes: %kernel.debug%
        entity_managers:
            default:
                mappings:
                  KnplabsSymfony2BundlesBundle: ~
