imports:
    - { resource: config.yml }

zend.config:
    loader:
        priority: notice
        path:     %kernel.logs_dir%/%kernel.environment%.log
    logger:
        path:     %kernel.logs_dir%/%kernel.environment%.log

app.config:
    router:   { resource: "%kernel.root_dir%/config/routing_dev.yml" }
    profiler:
        only_exceptions: false

webprofiler.config:
    toolbar: true
    intercept_redirects: false
