imports:
    - { resource: config_test.yml }

doctrine:
    dbal:
        connections:
            default:
                driver:   pdo_mysql
                dbname:   s2b_test
                user:     root
                password: ~
