homepage:
    pattern:        /
    defaults:       { _controller: S2bBundle:Main:index }

bundle_add:
    pattern:        /bundle/add
    defaults:       { _controller: S2bBundle:Bundle:add }

bundle_list:
    pattern:        /bundle/:sort
    defaults:       { _controller: S2bBundle:Bundle:listAll, sort: score }

user_list:
    pattern:        /developer
    defaults:       { _controller: S2bBundle:User:listAll }

search:
    pattern:        /search
    defaults:       { _controller: S2bBundle:Bundle:search }

latest:
    pattern:        /latest.:_format
    defaults:       { _controller: S2bBundle:Bundle:listLatest }
    requirements:   { _format: "(atom)" }

bundle_show:
    pattern:        /:username/:name
    defaults:       { _controller: S2bBundle:Bundle:show }

user_show:
    pattern:        /:name
    defaults:       { _controller: S2bBundle:User:show }
