homepage:
    pattern:        /
    defaults:       { _controller: S2bBundle:Main:index }

all:
    pattern:        /all
    defaults:       { _controller: S2bBundle:Bundle:listAll }

bundle_show:
    pattern:        /:username/:name
    defaults:       { _controller: S2bBundle:Bundle:show }
