homepage:
    pattern:        /
    defaults:       { _controller: S2bBundle:Main:index }

all:
    pattern:        /all/:sort
    defaults:       { _controller: S2bBundle:Bundle:listAll, sort: score }

bundle_show:
    pattern:        /:username/:name
    defaults:       { _controller: S2bBundle:Bundle:show }

search:
    pattern:        /search
    defaults:       { _controller: S2bBundle:Bundle:search }
