parameters:
    kernel.include_core_classes: false

kernel.config:
    charset:             UTF-8
    error_handler_level: null

web.config: ~

web.templating:
    escaping:       htmlspecialchars
    assets_version: SomeVersionScheme
