imports:
    - { resource: config_dev.yml }

doctrine_odm.mongodb:
    default_document_manager: default
    cache_driver:             array
    document_managers:
        default:
            connection: mongodb
    connections:
        mongodb:
            server:           localhost
            default_database: symfony2bundles
