parameters:
    kernel.include_core_classes: false

kernel.config:
    charset:             UTF-8
    error_handler_level: null

web.config:
    validation:
        enabled: true
        annotations: true

web.templating:
    escaping:       htmlspecialchars

markdown.parser: ~      # Enable the parser service

# doctrine.dbal:
#     dbname:   xxxxxxxx
#     user:     root
#     password: ~
# 
# doctrine.orm: ~
# 
# swift.mailer:
#     transport: gmail
#     username:  xxxxxxxx
#     password:  xxxxxxxx
