app.config:
    charset:       UTF-8
    error_handler: null
    csrf_secret:   betterPuttingThisInTheLocalConfigFile
    router:        { resource: "%kernel.root_dir%/config/routing.yml" }
    validation:    { enabled: true, annotations: true }
    templating:    {} #assets_version: SomeVersionScheme
    user:
        default_locale: en
        name:     SYMFONY
        type:     Native
        lifetime: 3600


# Twig Configuration
twig.config:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%

markdown.parser: ~      # Enable the parser service

#time.helper: ~      # Enable the time helper

s2b.config: ~
menu.twig: ~

#Twig need to be updated
#gravatar.config: ~


doctrine.orm:
    auto_generate_proxy_classes: %kernel.debug%
    mappings:
      S2bBundle: ~
# doctrine.dbal:
#     dbname:   xxxxxxxx
#     user:     root
#     password: ~
# 
# doctrine.orm: ~
# 
# swift.mailer:
#     transport: gmail
#     username:  xxxxxxxx
#     password:  xxxxxxxx
