imports:
    - { resource: config.yml }

zend.logger:
    priority: notice
    path:     %kernel.logs_dir%/%kernel.environment%.log

web.config:
    profiler: { only_exceptions: false }
    router:   { resource: "%kernel.root_dir%/config/routing_dev.yml" }

webprofiler.config:
    toolbar: true
    intercept_redirects: false
