imports:
    - { resource: config.yml }

zend.logger:
    priority: debug
    path:     %kernel.logs_dir%/%kernel.environment%.log

web.config:
    profiler: { only_exceptions: false }

webprofiler.config:
    toolbar: true
    intercept_redirects: true
