app.config:
    charset:       UTF-8
    error_handler: null
    csrf_secret:   betterPuttingThisInTheLocalConfigFile
    router:        { resource: "%kernel.root_dir%/config/routing.yml" }
    validation:    { enabled: true, annotations: true }
    templating:
        escaping:       htmlspecialchars
    user:
       default_locale: en
       session:
           name:     SYMFONY
           type:     Native
           lifetime: 3600

markdown.parser: ~      # Enable the parser service

time.helper: ~      # Enable the time helper

menu.templating: ~

gravatar.config: ~

s2b.config: ~

doctrine.orm:
  default_entity_manager:   default
  cache_driver:             apc           # array, apc, memcache, xcache
  entity_managers:
    default:
      connection:           default

# doctrine.dbal:
#     dbname:   xxxxxxxx
#     user:     root
#     password: ~
# 
# doctrine.orm: ~
# 
# swift.mailer:
#     transport: gmail
#     username:  xxxxxxxx
#     password:  xxxxxxxx
